### ISSUE TITLE
Return to home page on click on logo

### ISSUE THREAD

**Issue by shubhagarwal1** [GDSC-RCCIIT/gdg-website#80]

**Comment by MastanSayyad** [comment]
@shubhagarwal1, this is a minor issue, similar to #77, #78, and #79. You could have raised one issue for all these minor changes instead of creating separate ones.

There’s no need to create individual issues for such small components. Instead, create a single issue and clearly explain all the minor changes you'd like to propose. 

As a top ranker, your profile is evaluated more closely, so when we review, a lot of points will be reduced if your PRs aren’t meaningful.

Please close the mentioned issues and create only one for them. You can create as many issues as you want, but they need to be meaningful. I hope you understand that.

@rishicds add me as a collaborator need to fix some labels

**Comment by shubhagarwal1** [comment]
Hey @MastanSayyad, Thank you for your feedback. I understand your concern regarding the separation of minor changes into multiple issues. My intent was to ensure each component’s specific modification was clearly documented for easier tracking and resolution. However, I see how consolidating them into a single issue could streamline the process and reduce unnecessary clutter in the issue tracker.

I’ll close #77, #78, and #79, and create one comprehensive issue detailing all the minor changes. Moving forward, I will ensure that smaller, related changes are grouped together to maintain meaningful contributions. Thank you for your guidance.

**Comment by rishicds** [comment]
given @MastanSayyad
